#!/bin/bash
#TTOTO funguje
#create env
module add conda-modules-py37
conda activate /storage/plzen1/home/ayshi/envs/overcooked_ai_terminal 

cd /storage/plzen1/home/ayshi/coding/
#mkdir premek2
#cd premek2
#git clone https://github.com/PremekBasta/PPO.git
#rm /storage/plzen1/home/ayshi/coding/premek2/PPO/overcooked_pytorch_stable_baselines/overcooked_ai/src/overcooked_ai_py/diverse_population/models/forced_coordination/POP_SMALL8/00.zip 
export CODEDIR=$(pwd)
echo $CODEDIR
export PROJDIR=/storage/plzen1/home/ayshi/coding/PPO/overcooked_pytorch_stable_baselines/overcooked_ai/src/overcooked_ai_py
echo $PROJDIR
cd PPO/overcooked_pytorch_stable_baselines/overcooked_ai/src/overcooked_ai_py

python diverse_population/diverse_pool_build.py --layout_name=$layout_name --trained_models=$trained_models --mode=$mode --exp=$exp --eval_set_name=$eval_set_name --init_SP_agents=$init_SP_agents --kl_diff_loss_coef=$kl_diff_loss_coef --kl_diff_loss_clip=$kl_diff_loss_clip --kl_diff_bonus_reward_coef=$kl_diff_bonus_reward_coef --kl_diff_bonus_reward_clip=$kl_diff_bonus_reward_clip --seed=$seed --n_sample_partners=$n_sample_partners > "$SCRATCHDIR"/out.txt 2> "$SCRATCHDIR"/err.txt

echo "python dobehl"
#pouze aktivuji svoje rpostredi
# a pridavam kopirovnai
INFODIR=/storage/plzen1/home/ayshi/coding/results
date_name=$(date +%m%d-%H%M)
echo "job id"
echo "$PBS_JOBID"
ls "$SCRATCHDIR"
cp "$SCRATCHDIR"/out.txt "$INFODIR"/"$datename"."$PBS_JOBID"_out.txt
cp "$SCRATCHDIR"/err.txt "$INFODIR"/"$datename"."$PBS_JOBID"_err.txt

echo "skopirovano"
rm -rf "$SCRATCHDIR"/*

