#!/bin/bash

file_names=$(ls $HOME/coding/results/ | tail -3 | head -2)

for f in $file_names; do
	echo "*********************************************************************************************"
	echo $f
	echo "*********************************************************************************************"
	cat $HOME/coding/results/"$f"
done


